name: Go CI/CD Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24' # Matches your Dockerfile

    - name: Install Dependencies
      run: go mod download

    - name: Build Go App
      run: go build -v ./cmd/server/main.go

    - name: Docker Build Check
      run: docker build -t sentrygo-test .